formats: ["bed", "inveRsion", "raw", "vcf.gz"]


# PET0628 excluded because it is an outlier on PCA
# < 30% of aligned reads reported in Todesco, et al. 2020
pet_exclusions: ["PET0628"]

datasets:
  dgrp2:
    chromosomes: ["2L", "2R", "3R", "3L"]
  ag1000g:
    chromosomes: ["2L", "2R", "3L"]
    populations: ["bfaso", "bfaso_gambiae", "bfaso_coluzzii"]
  h_petiolaris:
    chromosomes: ["Ha412HOChr05", "Ha412HOChr09", "Ha412HOChr11", "Ha412HOChr17"]
